services:
  db:
    image: dichor94/sqlconcesionario:v1
    container_name: contenedorbbddconcesionario
    ports:
      - "3306:3306"

  php:
    image: dichor94/phpconcesionario:v1
    container_name: contenedorphpconcesionario
    ports:
      - "8080:80"
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: concesionario1234
    ports:
      - "8081:80"
    depends_on:
      - db