services:
  db:
    image: dichor94/sqlconcesionario:v1
    container_name: contenedorbbddconcesionario
    ports:
      - "3306:3306"

  php:
    image: dichor94/phpconcesionario:v1
    container_name: contenedorphpconcesionario
    ports:
      - "8080:80"
    depends_on:
      - db
  
